### PR TITLE
fix:blocksyncer statement policy id

### PR DESCRIPTION
**Pull request by constwz**
### Description

add a description of your changes here...

### Rationale

tell us why we need these changes...

### Example

add an example CLI or API response...

### Changes

Notable changes: 
* add each change in a bullet point here
* ...

### CODE REVIEW

**Review by sysvm — APPROVED** [review]
LGTM

**Comment by xibao-nr** [comment]
If you have time, you can polish the description～

**Comment by xibao-nr** [comment]
You can add a space after the colon for a nicer look.

**Comment by will-2012** [comment]
You can add a space after the colon for a nicer look.

**Pull request merged**
