### PR TITLE
fix: adjust sp command description

### PR DESCRIPTION
**Pull request by sysvm**
### Description

Adjust SP commands description.

### Rationale

For better description format,

### Example

`./gnfd-sp list.modules -h`

### Changes

Notable changes: 
* N/A

### CODE REVIEW

**Comment by will-2012** [comment]
Fix the failed action.

**Comment by sysvm** [comment]
> Fix the failed action.

fixed

**Review by will-2012 — APPROVED** [review]

**Comment by will-2012** [comment]
Why submit a PR to the master branch?

**Review by will-2012 — CHANGES_REQUESTED** [review]
Why submit a PR to the master branch?

**Comment by sysvm** [comment]
> Why submit a PR to the master branch?

fixed

**Review by will-2012 — APPROVED** [review]

**Review by flywukong — APPROVED** [review]

**Pull request merged**
